apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.application.name }}-config
  namespace: {{ .Values.application.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.application.name }}
    app.kubernetes.io/component: backend

data:
  JWT_EXPIRE_MINUTES: {{ .Values.config.jwtExpireMinutes | quote }}
  AWS_REGION: {{ .Values.config.awsRegion | quote }}
  S3_BUCKET_NAME: {{ .Values.config.s3BucketName | quote }}
  SNS_TOPIC_ARN: {{ .Values.config.snsTopicArn | quote }}
