apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: project-hub-eks-aws-secrets
  namespace: {{ .Values.application.namespace }}

spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.config.awsRegion | quote }}

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: project-hub-eks-backend-secrets
  namespace: {{ .Values.application.namespace }}

spec:
  refreshInterval: 15m

  secretStoreRef:
    name: project-hub-eks-aws-secrets
    kind: SecretStore

  target:
    name: {{ .Values.secret.name }}
    creationPolicy: Owner

    template:
      type: Opaque

      data:
        DATABASE_URL: >-
          postgresql+psycopg2://{{ "{{ .DB_USERNAME }}" }}:{{ "{{ .DB_PASSWORD }}" }}@{{ .Values.config.database.host }}:{{ .Values.config.database.port }}/{{ .Values.config.database.name }}
        JWT_SECRET_KEY: "{{ "{{ .JWT_SECRET_KEY }}" }}"

  data:
    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: {{ .Values.secret.aws.jwt.name }}
        property: JWT_SECRET_KEY

    - secretKey: DB_USERNAME
      remoteRef:
        key: {{ .Values.secret.aws.database.name }}
        property: username

    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.secret.aws.database.name }}
        property: password
