apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}-backend
  namespace: {{ .Values.application.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.application.name }}
    app.kubernetes.io/component: backend

  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8000"

spec:
  type: {{ .Values.service.type }}

  selector:
    app.kubernetes.io/name: {{ .Values.application.name }}
    app.kubernetes.io/component: backend

  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
